### ISSUE TITLE
wrong shell command in shell/SASRec/test_amazon.sh

### ISSUE THREAD

**Issue by Jimmy9713** [rlqja1107/MELT#1]
line 3:
`python main.py --inference true --model **FMLP** --batch_size 128 --dataset $data --gpu $gpu --pareto_rule 0.8`

i suppose the model variable should be SASRec instead of FMLP (since it locates in SASRec directory)

**Comment by rlqja1107** [comment]
Thank you for your interest of my work.
I'd fix it by reflecting your point.
