### ISSUE TITLE
"ValueError: low >= high" when Train the MELT framework

### ISSUE THREAD

**Issue by cizhouyu** [rlqja1107/MELT#2]
Hello, thank you for your work and the open source code!
I encountered a small problem:
When i train the MELT framework on Music dataset with pretrained SASRec download from [SASRec_Music.pth](https://drive.google.com/drive/folders/1SKpdN_mAyMJgLTLSbqJOi3C9b8zm9Gbp?usp=sharing), an error message as shown in the figure occurs.
![image](https://github.com/rlqja1107/MELT/assets/60316519/fc7afeed-9bb3-4f48-b0ba-5f57eb826d7b)
I set the hyperparameters as follows in shell/MELT_SASRec/train_amazon.sh
```bash
gpu=2 # GPU num
data="Music" # Clothing, Sports, Beauty, Grocery, Automotive, Music

# ========Hyperparameter==========
lamb_u=0.2
lamb_i=0.3
e_max=180
# ================================
python main.py --inference false --dataset $data --gpu $gpu --model MELT_SASRec --lamb_u $lamb_u --lamb_i $lamb_i --e_max $e_max --pareto_rule 0.2 --batch_size 128
```
What's the problem? How do I train MELT correctly?
Thanks a lot!

**Comment by cizhouyu** [comment]
In the shell/MELT_SASRec/ folder, you may accidentally spell [test_amaozn.sh](https://github.com/rlqja1107/MELT/blob/master/shell/MELT_SASRec/test_amaozn.sh) instead of test_amazon.sh

**Comment by rlqja1107** [comment]
Hello, Cizhou Yu.

Thank you for your interest of my work (code).
I'd fix the name of test_amazon.sh.

For the next problem about the error, i am gonna check this error.
However, the submission deadline of my work is until next week. So, Can i check this error after that deadline?

**Comment by cizhouyu** [comment]
Sure! Good luck to you! Looking forward to your reply after the submission deadline

**Comment by cizhouyu** [comment]
When I adjust the hyperparameter ```--pareto_rule``` from the recommended 0.2 to 0.5, the variance ```user_threshold``` increases from 1 to 2, and the program can run normally without error from ```R = np.random.randint(1, user_thres, len(full_seq))```. But I don't know what impact this will have on performance.
In addition, there is a small question: under the same configuration, are the ```pareto_rule``` used in train and inference procedure the same value?

**Comment by rlqja1107** [comment]
Thank you for waiting response. When i run the bash code of shell/MELT_SASRec/train_amazon.sh, it runs successfully.
![image](https://github.com/rlqja1107/MELT/assets/55014424/cbfcd171-9557-4b8f-ad82-7f7c8a9c4a25)
I think you need to change the Pareto to 0.8, which means that 80% belongs to tail group and 20% belongs to head group.
However, if it is set to 0.2, tail group and head group are interchagned.
For answering the small question, `pareto_rule` is equally adopted in inference procedure.

Thank you for your interest.

**Comment by cizhouyu** [comment]
Okay, I understand. Thank you for your answer!
